//Daniel Juanda // 2001586262 // // //
//HUMAN MALE

#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <fstream>
#include "accountData.h" // call header file accountData.h which contain struct and link to here.

void main_Menu();
bool login_validation(string usrName, string pin);
void login_page();
void forgot_password();
void clearScreen();
void account_Page();
//void sleep(unsigned);

int main()
{
    clearScreen();
    main_Menu(); // call main_menu();



    return 0;
}

void main_Menu()
{
    int choice;
    cout << "-------------------------------------------------------------" << endl;
    cout << "                       WELCOME TO                            " << endl;
    cout << "                   BANK CENTRAL AFRICA                       " << endl;
    cout << "                     ONLINE BANKING                          " << endl;
    cout << "-------------------------------------------------------------" << endl;


    cout << "1.\t LOGIN" << endl;
    cout << "2.\t FORGOT PASSWORD" << endl;
    cout << "Enter your choice (1-2)" << endl;
    cin >> choice;
    while (choice <0 || choice >3) // Validate input
    {
        cout << "INVALID INPUT, PLEASE ENTER 1 OR 2 ONLY\n";
        cin >> choice;
    }
    switch (choice) {
        case 1:  login_page(); // if user input '1' then call function login_page
            break;
        case 2: forgot_password(); // if user input '2' then call function forgot_password
            break;

    }
    void ClearScreen();
}

void login_page()
{
    accountData login;
    string username, password;
    clearScreen();                              // call clear screen
    accountData logindata;                      // declare logindata class
    bool validateLogin=false;					// set initial value of validateLogin as false
    // declare string variables as input for argument login_Validatio
    do{								        			// do while syntax .. .
        cout << "Enter Username : \n";  				// prompt user to input username
        cin >> username;        			// store nameLogin string
        cout << "Enter Password : \n";	    			// prompt user to input username
        cin >> password;   					// store passLogin string
        validateLogin = login_validation(username,password);

        if(validateLogin ==1) 						// if validateLogin accept true value then proceed
        {
            clearScreen();							// clear screen
            account_Page();							// go to account_Page function
        }
        else
            cout << "INVALID INPUT. ENTER CORRECT USERNAME/PASSWORD!.\n"; //display if login input is false

    }while(validateLogin!=1); // keep repeating loop while login input aren't correctly entered.

}

void forgot_password()
{
    bool goOn=false; // initial value set to false
    int choice; // variable to store user's choice
    clearScreen(); // call clearScreen function
    const int MIN_VALUE = 1000000; // set min value of random-number generated
    const int MAX_VALUE = 9999999; // max value of random-numer generated
    int ticket_Number;             // declare ticket_Number variable
    unsigned seed = (unsigned int) time(0);        // seed generated by time

    srand(seed);

    ticket_Number = (rand() % (MAX_VALUE - MIN_VALUE + 1)) + MIN_VALUE; // formula to generate random-number
    cout << "--------------------------------------------\n";           // display
    cout << "          WE'VE MADE YOU A TICKET           \n";           // display
    cout << "\t  Ticket Number : " << ticket_Number << endl;            // display
    cout << "PLEASE KEEP THIS TICKET NUMBER TO CONTACT US.\n";          // display
    cout << "--------------------------------------------\n";           // display


    do {        // do start

        cout << "Enter 1 to Main Menu" << endl;     // display choice 1
        cout << "Enter 2 to Exit" << endl;          // display choice 2
        cin >> choice;                              // prompt user to enter choice;

        switch (choice){                            // switch statement start

            case 1 : {                              // case 1
                goOn = true;                        //
                clearScreen();                      // clear screen func
                main_Menu();                        // go to main_Menu()
                break;                              // break statement if case 1 fulfill
            }
            case 2 :{                               // case 2
                cout << "Exit Now.";                // display exit
                break;                              // break statement ifcase 2 fulfill
            }

            default : {                                             // default switch
                cout <<"INVALID INPUT. ENTER 1 OR 2 ONLY!.";        // display
                break;                                              // break
            }
        }

    }while (goOn);
}

bool login_validation(string usrName, string pin)
{
    accountData logindata;
    ifstream data;
    data.open("LoginData.txt");
    // here open file to replace the test


        bool validate = 0; //set initial boolean validate value to false.
        if (usrName == "test" && pin == "testpass") // condition if
        {
            return validate = true; // bool return true if the usrName and pin input are correct.
        } else {
            return validate = false; //flaggg , bool return false if the usrName and pin input are correct

        }


}

void clearScreen() //function to clear the screen
{
    cout << string( 100, '\n' );
}

void account_Page(){ // start func account_Page()
    accountData logindata;
    int choice;
    ifstream userAccount;
    if(userAccount.good()){
        userAccount.open("userDetails.txt");
    }
    else {
        cout << "SOME FILES ARE MISSING. PLEASE CONTACT ADMINISTRATOR!.\n";
    }


    clearScreen();
    string usrName, usrBalance;
    getline(userAccount, usrName, '|');
    cout << "---------------------------------------------------\n";
    cout << "Hi, " << usrName << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "---------------------------------------------------\n";


    cout << "1. Check Balance \n";
    cout << "2. Funds Transfer \n";
    cout << "3. Select Payment \n";
    cout << "4. Mini Statements \n";
    cout << "5. Account Settings \n";
    cout << "6. Cancel \n";

    cout << "Enter your choice: \n";

    cin >> choice;

    userAccount.close();

} // end func account_Page()

void check_Balance(){
    clearScreen();
    ifstream accountDetails; // get balanceData from text file..

    cout << "Your Balance is : \n";

}

int cancel_Select(){

    cout << "Exit Now...";
    return 0;

}




/*void date_Time() {
	time_t now = time(0);
	char* dt = ctime(&now);

	cout << dt;
}*/
